stages:
  - build

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

android:
  image: cirrusci/flutter:stable
  stage: build
  before_script:
    - echo $KEYSTORE | base64 -d > android/keystore.jks
    - echo "storeFile=keystore.jks" > android/key.properties
    - echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
    - echo "keyAlias=$ALIAS" >> android/key.properties
    - echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
  script:
    - flutter packages get
    - flutter build apk --release
  artifacts:
    when: on_success
    paths:
    - build/app/outputs/apk/release/app-release.apk

