name: CI

on: [push]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - name: Install Flutter SDK from source
      run: |
        cd $HOME
        git clone -b stable https://github.com/flutter/flutter.git
    - name: Pre-download development binaries
      run: $HOME/flutter/bin/flutter precache
    - uses: actions/checkout@v1
    - name: Download application dependencies
      run: $HOME/flutter/bin/flutter pub get
    - name: Test build
      run: $HOME/flutter/bin/flutter build ios --release --no-codesign
  build-android:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Flutter SDK from source
      run: |
        cd $HOME
        git clone -b stable https://github.com/flutter/flutter.git
    - name: Pre-download development binaries
      run: $HOME/flutter/bin/flutter precache
    - uses: actions/checkout@v1
    - name: Download application dependencies
      run: $HOME/flutter/bin/flutter pub get
    - name: Test build
      run: $HOME/flutter/bin/flutter build apk --debug
