name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter SDK from source
      run: |
        cd $HOME
        git clone -b stable https://github.com/flutter/flutter.git
    - name: Pre-download development binaries
      run: $HOME/flutter/bin/flutter precache
    - name: Accept Android Development Licenses
      run: yes | sdkmanager --licenses
    - name: Validate Flutter SDK is installed correctly
      run: $HOME/flutter/bin/flutter doctor
