name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter SDK from source
      run: |
        cd $HOME
        git clone -b stable https://github.com/flutter/flutter.git
        export PATH="$PATH:$HOME/flutter/bin"
    - name: Pre-download development binaries
      run: flutter precache
    - name: Validate Flutter SDK is installed correctly
      run: flutter doctor
